# Generated by Django 4.2 on 2023-04-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('url', models.URLField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('custom_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('created', models.DateTimeField()),
                ('edited', models.DateTimeField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('custom_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
