# Generated by Django 4.2 on 2023-04-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swFavorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
