# Generated by Django 4.2 on 2023-04-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swFavorites', '0002_alter_movie_custom_name_alter_planet_custom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_favorite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='is_favorite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
