# Generated by Django 4.2 on 2023-04-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swFavorites', '0003_alter_movie_is_favorite_alter_planet_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='updated',
            new_name='edited',
        ),
    ]
