# Generated by Django 4.2 on 2023-04-06 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swFavorites', '0004_rename_updated_movie_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='custom_name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='custom_name',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='is_favorite',
        ),
        migrations.CreateModel(
            name='UserMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(blank=True, default=False, null=True)),
                ('custom_name', models.CharField(blank=True, max_length=100, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swFavorites.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
