# Generated by Django 4.2 on 2023-04-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swFavorites', '0006_userplanet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplanet',
            old_name='movie',
            new_name='planet',
        ),
    ]
