# Generated by Django 4.2 on 2023-04-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swFavorites', '0007_rename_movie_userplanet_planet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovie',
            name='user',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='userplanet',
            name='user',
            field=models.CharField(max_length=8),
        ),
    ]
